
// ******************************************************** //
// THIS CODE WAS AUTO GENERATED BY 'AliasesConfigGenerator' //
// ******************************************************** //

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Modules.ReferenceDb_Public
{
    //
    // All variables here are supposed to be used at runtime and are subject to change after refreshing ReferenceDB.
    // DO NOT serialize any field value directly. Use string aliases instead.
    //

    public class ReferenceDbAliasesConfig
    {   
    
		// ActionConfigs //

		public const int Action_Example = 0;

		// AbilityConfigs //

		public const int Ability_MobAttack = 1;

		// DamageDispatchers //

		public const int DamageDispatcher_Default = 2;
		public const int DamageDispatcher_MobAttack = 3;

		// Characters //

		public const int Character_Player = 4;
		public const int Character_Test_AI = 5;

		// Dictionaries //

		// *****************************
		// GetId 
		// *****************************
		public int GetId(string _alias)
		{
		   bool success = dictAliasToId.TryGetValue(_alias, out int result);
		   if(!success)
		   {
		        Debug.Assert(false, $"Alias={_alias} was not found at ReferenceDb!");
		   } 
		   return result;
		}

		private readonly Dictionary<string, int> dictAliasToId = new()
		{
		    { "Action_Example", 0 },
		    { "Ability_MobAttack", 1 },
		    { "DamageDispatcher_Default", 2 },
		    { "DamageDispatcher_MobAttack", 3 },
		    { "Character_Player", 4 },
		    { "Character_Test_AI", 5 },

		};

    }
    
    // CATEGORY ENUMS:
    /// <summary>
    /// Elements of 'ACTIONCONFIGS' category.
    /// DO NOT serialize this enum.
    /// </summary>
    public enum CATEGORY_ACTIONCONFIGS
    {
		Action_Example = 0,

    }
    /// <summary>
    /// Elements of 'ABILITYCONFIGS' category.
    /// DO NOT serialize this enum.
    /// </summary>
    public enum CATEGORY_ABILITYCONFIGS
    {
		Ability_MobAttack = 1,

    }
    /// <summary>
    /// Elements of 'DAMAGEDISPATCHERS' category.
    /// DO NOT serialize this enum.
    /// </summary>
    public enum CATEGORY_DAMAGEDISPATCHERS
    {
		DamageDispatcher_Default = 2,
		DamageDispatcher_MobAttack = 3,

    }
    /// <summary>
    /// Elements of 'CHARACTERS' category.
    /// DO NOT serialize this enum.
    /// </summary>
    public enum CATEGORY_CHARACTERS
    {
		Character_Player = 4,
		Character_Test_AI = 5,

    }
}
